### ISSUE TITLE
Locked wallet message always shown

### ISSUE THREAD

**Issue by hriad** [BITCORNProject/Bitcorn-Test#1]
Misleading message: `Info: Minting suspended due to locked wallet`

That notice should disappear once wallet has been unlocked.

Although wallet has been unlocked (Correctly reported as such in the status bar of the wallet); the notice still shows up
![Screenshot from 2019-12-19 01-10-57](https://user-images.githubusercontent.com/4347428/71133988-e541ee80-21fc-11ea-8287-f60390753d6c.png)

1. Start bitcorn-qt
2. Unlock wallet

bitcorn v3.0.0; prebuilt binary from github releases

Linux x86_64

Arch linux with GNOME Shell 3.34.2

**Comment by proteanx** [comment]
Closing issue as it relates to the blockchain not yet being at Proof-of-Stake height and is no longer relevant.
